name: Build SmartCut Result

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # Runs every hour; adjust as needed
  workflow_dispatch:

jobs:
  build-smartcut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build-smartcut script
        # env:
        #   SMARTCUT_API_KEY: ${{ secrets.SMARTCUT_API_KEY }}
        run: npx ts-node scripts/build-smartcut.ts

      - name: Commit and push updated smartcut.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/smartcut.json
          git commit -m "Update smartcut result" || echo "No changes to commit"
          git push
